version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - cd web
      - echo Installing packages
      - npm install
  pre_build:
    commands:
      - echo No pre-build steps to run
  build:
    commands:
      - echo Building and exporting the app
      - npm run build
artifacts:
  files:
    - "**/*"
  base-directory: "web/out"
